### ISSUE TITLE
有关制作的Sim数据集的问题

### ISSUE THREAD

**Issue by xieyuankun** [yzyouzhang/Empirical-Channel-CM#2]
SIM数据集显示有10个不同设备的文件夹，但我注意到您另外一个项目代码中有写channel的意义是不同的压缩标准，devices的意义是不同的设备。
`   self.channel = ['amr[br=5k15]', 'amrwb[br=15k85]', 'g711[law=u]', 'g722[br=56k]',
                        'g722[br=64k]', 'g726[law=a,br=16k]', 'g728', 'g729a', 'gsmfr',
                        'silk[br=20k]', 'silk[br=5k]', 'silkwb[br=10k,loss=5]', 'silkwb[br=30k]']`
您在论文中提到了channel的意思是不同的设备‘’In our simulation, we choose 12 out of 74 different device IRs and apply each of them to all utterances of ASVspoof2019LA‘’ 所以，我有点不明白channel是指更换压缩标准还是改变设备了。
我想问一下这个数据集在用simulator改变设备的同时有没有改变音频的压缩的标准或者其他的东西，还是仅仅改变了录音设备。
另外，如果您方便的话，能否提供一个这个项目的pre-trained model，谢谢。

**Comment by yzyouzhang** [comment]
您好，感谢提问。我们这篇文章的工作是分析channel对anti-spoofing的影响的，当时只用了device作为channel
在另一个项目里是针对ASVspoof2021 Challenge的，所以用了压缩标准
这个数据集已经公开了https://zenodo.org/record/5794671
pre-trained model可能需要过一阵再上传，如果你训练的时候遇到任何问题欢迎继续提问

**Comment by xieyuankun** [comment]
明白了，感谢您的回答。
